name = "volynx-qr-resolver"
main = "worker.js"
compatibility_date = "2026-01-01"

routes = [
  { pattern = "qr.volynx.world/*", zone_name = "volynx.world" }
]

[vars]
SUPABASE_FN_URL = "https://zdmpzrderifgqmqivjoy.supabase.co/functions/v1/qr-resolve"
